# Generated by Django 5.2.7 on 2025-10-27 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def create_initial_records(apps, schema_editor): 
    Category = apps.get_model('class', 'Semester') 
    Category.objects.get_or_create(code='4041', name='404-پاییز')
    Category.objects.get_or_create(code='4042', name='404-زمستان/بهار')
    Category.objects.get_or_create(code='4043', name='404-تابستان')
    Category.objects.get_or_create(code='4051', name='405-پاییز')
    Category.objects.get_or_create(code='4052', name='405-زمستان/بهار')
    Category.objects.get_or_create(code='4053', name='405-تابستان')
    Category.objects.get_or_create(code='4061', name='406-پاییز')
    Category.objects.get_or_create(code='4062', name='406-زمستان/بهار')
    Category.objects.get_or_create(code='4063', name='406-تابستان')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('unit', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('subject_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('student_count', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'A'), ('Closed', 'Cl'), ('Finished', 'F'), ('Created', 'Cr')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('section_image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='class.semester')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='class.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_status', models.CharField(choices=[('Blocked', 'B'), ('Active', 'A')], max_length=10)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='class.section')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_initial_records),
    ]
