# Generated by Django 5.2.7 on 2025-10-28 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def create_initial_records_semester(apps, schema_editor): 
    Category = apps.get_model('class', 'Semester') 
    Category.objects.get_or_create(code='4041', name='404-پاییز')
    Category.objects.get_or_create(code='4042', name='404-زمستان/بهار')
    Category.objects.get_or_create(code='4043', name='404-تابستان')
    Category.objects.get_or_create(code='4051', name='405-پاییز')
    Category.objects.get_or_create(code='4052', name='405-زمستان/بهار')
    Category.objects.get_or_create(code='4053', name='405-تابستان')
    Category.objects.get_or_create(code='4061', name='406-پاییز')
    Category.objects.get_or_create(code='4062', name='406-زمستان/بهار')
    Category.objects.get_or_create(code='4063', name='406-تابستان')
    
def create_initial_records_subject(apps, schema_editor): 
    Category = apps.get_model('class', 'Subject') 
    Category.objects.get_or_create(english_name='Neurology', persian_name='بیماری‌های مغز و اعصاب', unit=0.5, subject_image='subject/neurology-subject.jpg', description="نورولوژی شاخه‌ای از پزشکی است که به بررسی و درمان بیماری‌های سیستم عصبی می‌پردازد؛ سیستمی پیچیده شامل مغز، نخاع و اعصاب محیطی که کنترل حرکات، احساسات و عملکردهای حیاتی را بر عهده دارد. واحد اصلی آن نورون است که پیام‌های عصبی را از طریق ناقل‌های شیمیایی منتقل می‌کند و سلول‌های گلیال با حمایت و میلینه‌سازی به عملکرد آن کمک می‌کنند. سیستم عصبی محیطی شامل شاخه‌های سوماتیک و خودکار است؛ شاخه خودکار با بخش‌های سمپاتیک و پاراسمپاتیک، تعادل بدن را حفظ می‌کند. سد خونی–مغزی از مغز در برابر مواد سمی محافظت می‌نماید. بیماری‌های نورولوژیک شامل اختلالات مغزی (مانند سکته و صرع)، نخاعی، اعصاب محیطی و عضلات هستند. از نظر علت می‌توانند عروقی، دمیلینه‌کننده، دژنراتیو یا عفونی باشند. تشخیص بر پایه معاینه، تصویربرداری و تست‌های الکتروفیزیولوژیک است و درمان شامل دارو، توانبخشی یا جراحی می‌باشد.")
    Category.objects.get_or_create(english_name='Nephrology', persian_name='بیماری‌های کلیه', unit=1.5, subject_image='subject/nephrology-subject.jpg', description="نفرولوژی شاخه‌ای از پزشکی است که به مطالعه و درمان بیماری‌های کلیه می‌پردازد؛ اندامی حیاتی که با فیلتر کردن خون، تعادل آب، الکترولیت‌ها و اسید–باز بدن را حفظ می‌کند و در تنظیم فشارخون و تولید هورمون‌هایی مانند اریتروپویتین نقش دارد. هر کلیه از میلیون‌ها نفرون تشکیل شده است که شامل گلومرول و توبول‌های مختلف برای تصفیه و بازجذب مواد هستند. بیماری‌های کلیه به دو دستهٔ اصلی تقسیم می‌شوند: حاد (Acute Kidney Injury) که با کاهش ناگهانی عملکرد کلیه همراه است، و مزمن (Chronic Kidney Disease) که به تدریج موجب کاهش برگشت‌ناپذیر عملکرد کلیه می‌شود. علل شایع شامل دیابت، فشارخون بالا، گلومرولونفریت‌ها و بیماری‌های پلی‌کیستیک است. تظاهرات بالینی می‌تواند شامل خستگی، ادم، افزایش اوره و کراتینین خون و اختلالات الکترولیتی باشد. تشخیص بر اساس آزمایش ادرار، کراتینین سرم، سونوگرافی و گاهی بیوپسی کلیه انجام می‌شود. درمان شامل کنترل علت زمینه‌ای، تنظیم فشارخون و در مراحل پیشرفته، دیالیز یا پیوند کلیه است.")
    Category.objects.get_or_create(english_name='Gastroenterology', persian_name='بیماری‌های گوارش و کبد', unit=2.1, subject_image='subject/gastroenterology-subject.jpg', description="گاستروانترولوژی شاخه‌ای از پزشکی است که به بررسی، تشخیص و درمان بیماری‌های دستگاه گوارش و کبد می‌پردازد؛ دستگاهی که از دهان تا مقعد امتداد دارد و مسئول هضم، جذب و دفع مواد غذایی است. معده با ترشح اسید و آنزیم‌ها در هضم نقش دارد و در برابر این اسید، لایهٔ موکوسی محافظ وجود دارد. زمانی که این تعادل با مصرف NSAIDها یا عفونت H. pylori برهم می‌خورد، گاستریت و زخم پپتیک ایجاد می‌شود. در مری، ضعف اسفنکتر تحتانی باعث بازگشت اسید و بروز بیماری ریفلاکس (GERD) می‌گردد. در رودهٔ باریک، بیماری سلیاک با واکنش ایمنی علیه گلوتن موجب تخریب پرزها و سوء‌جذب می‌شود. التهاب مزمن روده در قالب دو بیماری اصلی دیده می‌شود: کولیت اولسراتیو (درگیری پیوستهٔ کولون) و کرون (التهاب قطعه‌قطعه و عمقی). اختلالات عملکردی مانند سندروم روده تحریک‌پذیر (IBS) بدون آسیب بافتی ولی با درد و نفخ بروز می‌کنند. در کبد، هپاتیت‌های ویروسی، الکلی و متابولیک از علل شایع التهاب هستند و در موارد مزمن می‌توانند به سیروز، نارسایی کبد یا کارسینوم منجر شوند.")
    Category.objects.get_or_create(english_name='Pulmonology', persian_name='بیماری‌های ریه', unit=1.9, subject_image='subject/pulmonology-subject.jpg', description="پولمونولوژی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های دستگاه تنفسی می‌پردازد؛ سیستمی که شامل راه‌های هوایی، ریه‌ها و عروق ریوی است و وظیفه تبادل اکسیژن و دی‌اکسیدکربن و حفظ هموستاز اسید–باز را بر عهده دارد. ریه‌ها از میلیون‌ها آلوئول تشکیل شده که محل اصلی تبادل گازها هستند و جریان خون از طریق مویرگ‌های ریوی اکسیژن را به سلول‌ها منتقل می‌کند. بیماری‌های ریه به دو دستهٔ حاد و مزمن تقسیم می‌شوند: عفونت‌های حاد مانند پنومونی و برونشیت، و بیماری‌های مزمن مانند آسم، بیماری مزمن انسدادی ریه (COPD) و فیبروز ریوی که به تدریج عملکرد تنفسی را کاهش می‌دهند. علل شایع شامل عفونت‌های باکتریایی و ویروسی، قرارگیری در معرض دود و آلاینده‌ها، و عوامل ژنتیکی است. علائم بالینی می‌تواند شامل تنگی‌نفس، سرفه، خلط و خستگی باشد. تشخیص بر اساس رادیوگرافی قفسه سینه، سی‌تی اسکن، اسپیرومتری و آزمایش‌های خون و گازهای شریانی انجام می‌شود. درمان شامل کنترل علت زمینه‌ای، دارودرمانی، اکسیژن‌درمانی و در موارد پیشرفته تهویه مکانیکی یا پیوند ریه است.")
    Category.objects.get_or_create(english_name='Cardiology', persian_name='بیماری‌های قلب و عروق', unit=1.9, subject_image='subject/cardiology-subject.jpg', description="قلب و عروق شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های قلب و سیستم گردش خون می‌پردازد؛ سیستمی که با پمپاژ خون به اندام‌ها، اکسیژن و مواد مغذی را منتقل و دی‌اکسیدکربن و مواد زائد را دفع می‌کند. قلب از چهار حفره شامل دو دهلیز و دو بطن تشکیل شده و با سیستم الکتریکی داخلی خود، ضربان منظم و هماهنگ ایجاد می‌کند. عروق شامل شریان‌ها، وریدها و مویرگ‌ها هستند که فشار خون و جریان خون را تنظیم می‌کنند. بیماری‌های قلبی به دو دستهٔ حاد و مزمن تقسیم می‌شوند: اختلالات حاد مانند انفارکتوس میوکارد و آریتمی‌های شدید، و بیماری‌های مزمن مانند نارسایی قلب، ایسکمی مزمن و پرفشاری شریانی. علل شایع شامل تصلب شرایین، فشارخون بالا، دیابت، چاقی و عوامل ژنتیکی است. علائم بالینی می‌تواند شامل درد قفسه سینه، تنگی‌نفس، خستگی، ادم و سبکی سر باشد. تشخیص بر پایه الکتروکاردیوگرام، اکوکاردیوگرافی، آنژیوگرافی و آزمایش‌های خونی انجام می‌شود. درمان شامل اصلاح سبک زندگی، دارودرمانی، مداخلات آنژیوپلاستی و جراحی قلب و در موارد پیشرفته پیوند قلب است.")
    Category.objects.get_or_create(english_name='Endocrinology-and-Metabolism', persian_name='بیماری‌های غدد درون‌ریز و متابولیسم', unit=1.9, subject_image='subject/endocrinology-and-metabolism-subject.jpg', description="اندوکرینولوژی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های غدد درون‌ریز و اختلالات متابولیک می‌پردازد؛ غددی که با ترشح هورمون‌ها، عملکردهای حیاتی بدن مانند رشد، متابولیسم، تنظیم قند خون و تولید مثل را کنترل می‌کنند. غدد مهم شامل تیروئید، پاراتیروئید، پانکراس، غدد فوق‌کلیوی، هیپوفیز و غده جنسی هستند. اختلالات غدد می‌توانند موجب کم‌کاری یا پرکاری هورمونی شوند، مانند دیابت نوع ۱ و ۲، کم‌کاری یا پرکاری تیروئید، سندروم کوشینگ و بیماری آدیسون. بیماری‌های متابولیک اغلب با اختلال در قند، چربی یا الکترولیت‌ها همراه‌اند و می‌توانند اثر سیستمیک روی قلب، کلیه و استخوان‌ها داشته باشند. علائم بالینی شامل خستگی، کاهش یا افزایش وزن، ضعف عضلانی، تغییرات فشارخون و اختلالات قندی است. تشخیص بر اساس آزمایش‌های هورمونی، تصویرسازی غدد و آزمون‌های تحریک یا مهاری انجام می‌شود. درمان شامل اصلاح سبک زندگی، دارودرمانی هورمونی، جراحی غدد و در صورت نیاز تنظیم دقیق متابولیسم است.")
    Category.objects.get_or_create(english_name='Rheumatology', persian_name='بیماری‌های بافت همبند و روماتیسمی', unit=1.5, subject_image='subject/rheumatology-subject.jpg', description="روماتولوژی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های بافت همبند و روماتیسمی می‌پردازد؛ بافت‌هایی که شامل مفاصل، رباط‌ها، تاندون‌ها، پوست و اندام‌های داخلی می‌شوند و پشتیبانی ساختاری و عملکردی بدن را فراهم می‌کنند. بیماری‌های روماتیسمی می‌توانند التهابی، خودایمنی یا دژنراتیو باشند و اغلب با درد مفصل، تورم، محدودیت حرکتی و خستگی همراه هستند. از شایع‌ترین بیماری‌ها می‌توان به آرتریت روماتوئید، لوپوس اریتماتوز سیستمیک (SLE)، اسکلرودرمی، پلی‌میوزیت و آرتروز اشاره کرد. علل شامل پاسخ ایمنی نابجای بدن، عوامل ژنتیکی و محیطی و اختلال در تولید یا عملکرد کلاژن و سایر پروتئین‌های بافت همبند است. بیماری‌ها ممکن است سیستمیک بوده و ارگان‌هایی مانند قلب، ریه و کلیه را درگیر کنند. تشخیص بر پایه معاینه بالینی، آزمایش‌های خودایمنی (ANA، RF، anti-CCP)، تصویربرداری مفصلی و در موارد خاص بیوپسی بافت است. درمان شامل دارودرمانی ضدالتهابی، سرکوب سیستم ایمنی، فیزیوتراپی و مدیریت علائم است و هدف آن کاهش التهاب، حفظ عملکرد مفاصل و پیشگیری از آسیب ارگان‌هاست.")
    Category.objects.get_or_create(english_name='Infectious-Diseases', persian_name='بیماری‌های عفونی و گرمسیری', unit=1, subject_image='subject/infectious-diseases-subject.jpg', description="عفونت‌شناسی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های ناشی از عوامل عفونی مانند باکتری‌ها، ویروس‌ها، قارچ‌ها و انگل‌ها می‌پردازد. این بیماری‌ها می‌توانند حاد یا مزمن، سیستمیک یا موضعی باشند و از طریق تماس مستقیم، هوا، غذا و ناقلین منتقل شوند. سیستم ایمنی میزبان نقش حیاتی در مهار و کنترل عفونت دارد و ضعف آن می‌تواند منجر به عفونت شدید یا فرصت‌طلب شود. بیماری‌های گرمسیری اغلب در مناطق خاص با شرایط محیطی و بهداشتی ویژه دیده می‌شوند و شامل مالاریا، تب دانگی، تیفوس و شیگلوز هستند. علائم بالینی شامل تب، خستگی، ضعف، درد عضلانی، اسهال و بثورات پوستی است و می‌تواند بسته به عامل عفونی متغیر باشد. تشخیص بر پایه آزمایش‌های میکروبیولوژیک، سرولوژی، PCR و تصویربرداری صورت می‌گیرد. درمان شامل داروهای ضد میکروبی، حمایت سیستمیک و در موارد شدید مراقبت ویژه است. پیشگیری از طریق واکسیناسیون، بهداشت محیط، کنترل ناقلین و رعایت اصول ایمنی غذایی و فردی اهمیت ویژه دارد.")
    Category.objects.get_or_create(english_name='Hematology-and-Oncology', persian_name='بیماری‌های خون و بدخیمی‌ها', unit=1.9, subject_image='subject/hematology-and-oncology-subject.jpg', description="هماتولوژی و انکولوژی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های خون، مغز استخوان و بدخیمی‌ها می‌پردازد. سیستم خونی شامل سلول‌های قرمز، سفید و پلاکت‌ها است که وظیفه حمل اکسیژن، دفاع ایمنی و انعقاد خون را بر عهده دارند. اختلالات خونی می‌توانند شامل کم‌خونی‌ها، پلی‌سیتمی، لوسمی‌ها، لنفوم‌ها و اختلالات انعقادی باشند و علائمشان شامل خستگی، خونریزی، کبودی و افزایش عفونت‌هاست. بدخیمی‌ها شامل تومورهای جامد و خونی بوده و رشد کنترل‌نشده سلول‌ها و متاستاز ویژگی اصلی آن‌هاست. تشخیص بر اساس آزمایش‌های خون، بیوپسی مغز استخوان، نمونه‌گیری تومور و تصویربرداری انجام می‌شود. درمان شامل شیمی‌درمانی، رادیوتراپی، ایمنی‌درمانی، دارودرمانی هدفمند و در برخی موارد پیوند سلول‌های بنیادی است. مدیریت این بیماران نیازمند نظارت دقیق بر عوارض درمان، حمایت تغذیه‌ای و کنترل عفونت‌هاست و هدف آن بهبود بقای بیمار و کیفیت زندگی است.")
    Category.objects.get_or_create(english_name='Pediatrics', persian_name='بیماری‌های کودکان', unit=1, subject_image='subject/pediatrics-subject.jpg', description="پزشکی اطفال شاخه‌ای از پزشکی است که به مراقبت، پیشگیری، تشخیص و درمان بیماری‌های نوزادان، کودکان و نوجوانان می‌پردازد. کودکان دارای ویژگی‌های فیزیولوژیک، متابولیک و ایمنی متفاوتی نسبت به بزرگسالان هستند که در تشخیص و درمان بیماری‌ها اهمیت دارد. بیماری‌های شایع شامل عفونت‌های تنفسی و گوارشی، بیماری‌های متابولیک و غددی، اختلالات رشد و کم‌خونی‌هاست. نوزادان و کودکان همچنین در معرض بیماری‌های ژنتیکی و مادرزادی قرار دارند که می‌تواند بر اندام‌ها و عملکرد سیستمیک تأثیر بگذارد. علائم بالینی ممکن است شامل تب، استفراغ، اسهال، اختلال رشد، بی‌حالی و تغییر در الگوی تغذیه و خواب باشد. تشخیص بر اساس معاینه دقیق بالینی، آزمایش‌های خون و ادرار، تصویربرداری و در صورت نیاز تست‌های ژنتیکی انجام می‌شود. درمان شامل دارودرمانی، حمایت تغذیه‌ای، واکسیناسیون، توانبخشی و مراقبت‌های ویژه در نوزادان و کودکان است. پیشگیری، آموزش والدین و پیگیری رشد و نمو کودک از ارکان اصلی پزشکی اطفال محسوب می‌شوند.")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_name', models.CharField(default=None, max_length=50, unique=True)),
                ('persian_name', models.CharField(default=None, max_length=50, unique=True)),
                ('unit', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('subject_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('student_count', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'A'), ('Closed', 'Cl'), ('Finished', 'F'), ('Created', 'Cr')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('section_image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='class.semester')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='class.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_status', models.CharField(choices=[('Blocked', 'B'), ('Active', 'A')], max_length=10)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectionstudents', to='class.section')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentsections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentsubjects', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectstudents', to='class.subject')),
            ],
        ),
        migrations.RunPython(create_initial_records_subject),
        migrations.RunPython(create_initial_records_semester),
    ]
