# Generated by Django 5.2.7 on 2025-11-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='unit',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
