# Generated by Django 5.2.7 on 2025-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsection',
            name='student_status',
            field=models.CharField(choices=[('Active', 'A'), ('Blocked', 'B')], max_length=10),
        ),
    ]
