# Generated by Django 5.2.7 on 2025-10-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='image',
            new_name='section_image',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
