# Generated by Django 5.2.7 on 2025-10-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_rename_image_section_section_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsection',
            name='student_status',
            field=models.CharField(choices=[('Blocked', 'B'), ('Active', 'A')], max_length=10),
        ),
    ]
