# Generated by Django 5.2.7 on 2025-11-08 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_alter_subject_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_name', models.CharField(default=None, max_length=50, unique=True)),
                ('persian_name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
