# Generated by Django 5.2.7 on 2025-11-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_alter_studentsection_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_image',
            field=models.ImageField(blank=True, default='defaults/default_section.jpg', null=True, upload_to='section/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_image',
            field=models.ImageField(blank=True, default='defaults/default_subject.jpg', null=True, upload_to='subject/'),
        ),
    ]
