# Generated by Django 5.2.7 on 2025-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='established_year',
            field=models.DateField(default='2020-02-02'),
            preserve_default=False,
        ),
    ]
