# Generated by Django 5.2.7 on 2025-11-17 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models

def create_initial_records_university(apps, schema_editor): 
    Category = apps.get_model('university', 'University')
    Category.objects.get_or_create(
        english_name="Isfahan_University_of_Medical_Sciences",
        persian_name="دانشگاه علوم پزشکی و خدمات بهداشتی درمانی استان اصفهان",
        type="Public University",
        established_year="1946-09-23",
        address="اصفهان - میدان آزادی - خیابان هزارجریب",
        city="isfahan",
        province="isfahan",
        phone_number="03136680048",
        email="info@mui.ac.ir",
        website="https://mui.ac.ir",
        rector_name="شاهین شیرانی",
        description="دانشگاه علوم پزشکی و خدمات بهداشتی درمانی استان اصفهان یکی از دانشگاه‌های دولتی تیپ یک ایران و تحت پوشش وزارت بهداشت، درمان و آموزش پزشکی در استان اصفهان است."
    )

def create_initial_records_faculty(apps, schema_editor): 
    Category = apps.get_model('university', 'Faculty')
    University = apps.get_model('university', 'University')
    university_name = "Isfahan_University_of_Medical_Sciences"
    university_record = University.objects.get(english_name=university_name)
    Category.objects.get_or_create(name="دانشکده بهداشت" ,phone_number="03136688628" ,email="info@hlth.mui.ac.ir" ,dean="فیروزه مصطفوی دارانی", university=university_record)
    Category.objects.get_or_create(name="دانشکده پرستاری و مامایی" ,phone_number="03136687153" ,email="webmaster@nm.mui.ac.ir" ,dean="محسن شهریاری", university=university_record)
    Category.objects.get_or_create(name="دانشکده پزشکی" ,phone_number="03136680048" ,email="dean@med.mui.ac.ir" ,dean="بیژن ایرج", university=university_record)
    Category.objects.get_or_create(name="دانشکده پیراپزشکی" ,phone_number="03136680048" ,email="info@pmed.mui.ac.ir" ,dean="بهمن رشیدی", university=university_record)
    Category.objects.get_or_create(name="دانشکده تغذیه و علوم غذایی" ,phone_number="03136688487" ,email="info@nutr.mui.ac.ir" ,dean="سید محمد حسین روحانی", university=university_record)
    Category.objects.get_or_create(name="دانشکده داروسازی و علوم دارویی" ,phone_number="03136688064" ,email="info@pharm.mui.ac.ir" ,dean="محسن مینائیان", university=university_record)
    Category.objects.get_or_create(name="دانشکده دندانپزشکی" ,phone_number="03137925552" ,email="info@dnt.mui.ac.ir" ,dean="سید محمد رضوی", university=university_record)
    Category.objects.get_or_create(name="دانشکده علوم توانبخشی" ,phone_number="03136693089" ,email="mostamand@rehab.mui.ac.ir" ,dean="جاوید مستمند", university=university_record)
    Category.objects.get_or_create(name="دانشکده فناوری های نوین علوم پزشکی" ,phone_number="03137923851" ,email="karbasi@med.mui.ac.ir" ,dean="سعید کرباسی", university=university_record)
    Category.objects.get_or_create(name="دانشکده مدیریت و اطلاع رسانی پزشکی" ,phone_number="03137923000" ,email="a_rahimi@mng.mui.ac.ir" ,dean="علیرضا رحیمی", university=university_record)
    Category.objects.get_or_create(name="مجتمع آموزش عالی سلامت شهرستان خمینی شهر" ,phone_number="03136680048" ,email="info@khedu.mui.ac.ir" ,dean="علی شریفی", university=university_record)

def create_initial_records_department(apps, schema_editor): 
    Category = apps.get_model('university', 'Department')
    Faculty = apps.get_model('university', 'Faculty')
    faculty_name = "دانشکده پزشکی"
    faculty_record = Faculty.objects.get(name=faculty_name)
    Category.objects.get_or_create(name="بیهوشی" ,head_of_department="مهرداد نورورزی", faculty=faculty_record)
    Category.objects.get_or_create(name="اورولوژی" ,head_of_department="مجید شیرانی", faculty=faculty_record)
    Category.objects.get_or_create(name="ارتوپدی" ,head_of_department="شیروان رستگار", faculty=faculty_record)
    Category.objects.get_or_create(name="اخلاق پزشکی" ,head_of_department="بهزاد شمس مورکانی", faculty=faculty_record)
    Category.objects.get_or_create(name="آسیب شناسی" ,head_of_department="آذر برادران", faculty=faculty_record)
    Category.objects.get_or_create(name="چشم پزشکی" ,head_of_department="علیرضا دهقانی", faculty=faculty_record)
    Category.objects.get_or_create(name="جراحی" ,head_of_department="مسعود ناظم", faculty=faculty_record)
    Category.objects.get_or_create(name="جراحی مغز و اعصاب" ,head_of_department="بهرام امین منصور", faculty=faculty_record)
    Category.objects.get_or_create(name="پوست" ,head_of_department="ذبیح اله شاهمرادی", faculty=faculty_record)
    Category.objects.get_or_create(name="پزشکی اجتماعی" ,head_of_department="پژمان عقدک", faculty=faculty_record)
    Category.objects.get_or_create(name="روانشناسی سلامت" ,head_of_department="رضا باقریان سراوردی", faculty=faculty_record)
    Category.objects.get_or_create(name="رادیولوژی" ,head_of_department="سمیه حاجی احمدی", faculty=faculty_record)
    Category.objects.get_or_create(name="رادیوآنکولوژی" ,head_of_department="مهناز رعایائی", faculty=faculty_record)
    Category.objects.get_or_create(name="داخلی اعصاب" ,head_of_department="فریبرز خوروش", faculty=faculty_record)
    Category.objects.get_or_create(name="داخلی" ,head_of_department="بیژن ایرج", faculty=faculty_record)
    Category.objects.get_or_create(name="طب فیزیکی و توانبخشی" ,head_of_department="بابک وحدت پور", faculty=faculty_record)
    Category.objects.get_or_create(name="طب اورژانس" ,head_of_department="فرهاد حیدری", faculty=faculty_record)
    Category.objects.get_or_create(name="سم شناسی بالینی" ,head_of_department="غلامرضا معصومی", faculty=faculty_record)
    Category.objects.get_or_create(name="زنان و زایمان" ,head_of_department="مينو موحدي", faculty=faculty_record)
    Category.objects.get_or_create(name="روانپزشکی" ,head_of_department="سیدغفور موسوی", faculty=faculty_record)
    Category.objects.get_or_create(name="گوش و حلق و بینی" ,head_of_department="نظام الدین برجیس", faculty=faculty_record)
    Category.objects.get_or_create(name="کودکان" ,head_of_department="مهدی قادریان", faculty=faculty_record)
    Category.objects.get_or_create(name="قلب و عروق" ,head_of_department="علیرضا خسروی", faculty=faculty_record)
    Category.objects.get_or_create(name="عفونی" ,head_of_department="فرزین خوروش", faculty=faculty_record)
    Category.objects.get_or_create(name="قارچ و انگل شناسی" ,head_of_department="حسین یوسفی", faculty=faculty_record)
    Category.objects.get_or_create(name="ژنتیک و بیولوژی ملکولی" ,head_of_department="محمدرضا شریفی", faculty=faculty_record)
    Category.objects.get_or_create(name="باکتری و ویروس شناسی" ,head_of_department="محمد شایسته پور", faculty=faculty_record)
    Category.objects.get_or_create(name="ایمنی شناسی" ,head_of_department="ناهید اسکندری", faculty=faculty_record)
    Category.objects.get_or_create(name="طب ایرانی" ,head_of_department="محمد انصاری پور", faculty=faculty_record)
    Category.objects.get_or_create(name="علوم تشریحی و بیولوژی تولید مثل" ,head_of_department="حسین صالحی", faculty=faculty_record)
    Category.objects.get_or_create(name="فیزیولوژی" ,head_of_department="نپتون سلطانی", faculty=faculty_record)
    Category.objects.get_or_create(name="فیزیک و مهندسی پزشکی" ,head_of_department="احمد شانئی", faculty=faculty_record)
    Category.objects.get_or_create(name="معارف اسلامی" ,head_of_department="قدرت الله مومنی وانانی", faculty=faculty_record)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dean', models.CharField(max_length=80)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_name', models.CharField(default=None, max_length=80, unique=True)),
                ('persian_name', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(choices=[('Public University', 'Public'), ('Islamic Azad University', 'Islamic Azad'), ('Non-Profit Non-Governmental University', 'Non-Profit Non-Governmental'), ('Payame Noor University', 'Payame Noor'), ('Applied Science and Technology', 'University of Applied Science and Technology'), ('Technical and Vocational University', 'Technical and Vocational')], max_length=80)),
                ('established_year', models.DateField()),
                ('address', models.TextField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('rector_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('head_of_department', models.CharField(max_length=80)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='university.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties', to='university.university'),
        ),
        migrations.RunPython(create_initial_records_university),
        migrations.RunPython(create_initial_records_faculty),
        migrations.RunPython(create_initial_records_department),
    ]
