# Generated by Django 5.2.7 on 2025-10-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='faculty_id',
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='university.faculty'),
        ),
    ]
