# Generated by Django 5.2.7 on 2025-11-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_department_faculty_id_department_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='name',
            new_name='english_name',
        ),
        migrations.AddField(
            model_name='university',
            name='persian_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
