# Generated by Django 5.2.7 on 2026-02-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_credit',
            field=models.IntegerField(default=0),
        ),
    ]
