# Generated by Django 5.2.7 on 2025-10-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
