# Generated by Django 5.2.7 on 2025-10-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
