# Generated by Django 5.2.7 on 2025-10-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_role',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
