# Generated by Django 5.2.7 on 2025-10-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0002_remove_user_verified_user_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
