# Generated by Django 5.2.7 on 2025-10-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0002_user_main_role_alter_user_personal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='registery.role'),
        ),
    ]
