# Generated by Django 5.2.7 on 2025-10-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0003_user_pass_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='done_scenarios',
            field=models.IntegerField(default=0),
        ),
    ]
