# Generated by Django 5.2.7 on 2025-10-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0004_user_done_scenarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/default_profile.png', null=True, upload_to='profile/'),
        ),
    ]
