# Generated by Django 5.2.7 on 2025-11-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/profile/default_profile.jpg', null=True, upload_to='profile/'),
        ),
    ]
