# Generated by Django 5.2.7 on 2025-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registery', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('پزشکی', 'Medicine')], default='پزشکی', max_length=30),
        ),
    ]
