user  nginx;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 2048;
}

http{
    upstream django_medicase {
        server medicase:8000;
    }

    server {
        listen 443 ssl;  # گوش دادن به پورت 443
        server_name _;
        
        # برای ریدایرکت، نیاز به یک گواهینامه SSL موقت یا ساختگی (dummy) دارید.
        # این خطوط موقتاً برای اینکه Nginx شروع به کار کند، لازم است.
        # در غیر این صورت Nginx بدون فایل SSL کرش می‌کند.
        ssl_certificate /etc/nginx/ssl/dummy.crt;
        ssl_certificate_key /etc/nginx/ssl/dummy.key;

        # ریدایرکت دائمی 301 به HTTP
        return 301 http://$host$request_uri;
    }
    
    server{
        listen 80;
        server_name _;

        access_log  /var/log/nginx/access.log;
        error_log   /var/log/nginx/error.log;

        location / {
            proxy_pass http://django_medicase;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_redirect off;
        }
    }
}