user  nginx;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 2048;
}

http{
    upstream django_medicase {
        server 0.0.0.0:8000;
    }

    server{
        listen 80;
        server_name 172.20.144.1;

        access_log  /var/log/nginx/access.log;
        error_log   /var/log/nginx/error.log;

        location / {
            proxy_pass http://django_medicase;
        }


    }
}