user  nginx;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 2048;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream django_medicase {
        server django_medicase:8000;
    }

    server {
        listen 80;
        server_name _;
        # server_name medicase-isfahan.com www.medicase-isfahan.com medicase-isfahan.ir www.medicase-isfahan.ir;

        access_log  /var/log/nginx/access.log;
        error_log   /var/log/nginx/error.log;

        location /api/ {
            proxy_pass http://django_medicase;
            proxy_http_version 1.1;
            proxy_redirect off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /app/MediCaseBack/staticfiles/;
        }

        location /media/ {
            alias /app/MediCaseBack/media/;
            expires 30d;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}