# Generated by Django 5.2.7 on 2025-11-22 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal

def create_initial_records_semester(apps, schema_editor): 
    Category = apps.get_model('classroom', 'Semester') 
    Category.objects.get_or_create(code='4041', name='404-پاییز')
    Category.objects.get_or_create(code='4042', name='404-زمستان/بهار')
    Category.objects.get_or_create(code='4043', name='404-تابستان')
    Category.objects.get_or_create(code='4051', name='405-پاییز')
    Category.objects.get_or_create(code='4052', name='405-زمستان/بهار')
    Category.objects.get_or_create(code='4053', name='405-تابستان')
    Category.objects.get_or_create(code='4061', name='406-پاییز')
    Category.objects.get_or_create(code='4062', name='406-زمستان/بهار')
    Category.objects.get_or_create(code='4063', name='406-تابستان')
    
def create_initial_records_subject(apps, schema_editor): 
    Category = apps.get_model('classroom', 'Subject') 
    Category.objects.get_or_create(english_name='Neurology', persian_name='بیماری‌های مغز و اعصاب', unit=Decimal('0.5'), subject_status='Inactive', subject_image='subject/neurology-subject.jpg', description="نورولوژی شاخه‌ای از پزشکی است که به بررسی و درمان بیماری‌های سیستم عصبی می‌پردازد؛ سیستمی پیچیده شامل مغز، نخاع و اعصاب محیطی که کنترل حرکات، احساسات و عملکردهای حیاتی را بر عهده دارد. واحد اصلی آن نورون است که پیام‌های عصبی را از طریق ناقل‌های شیمیایی منتقل می‌کند و سلول‌های گلیال با حمایت و میلینه‌سازی به عملکرد آن کمک می‌کنند. سیستم عصبی محیطی شامل شاخه‌های سوماتیک و خودکار است؛ شاخه خودکار با بخش‌های سمپاتیک و پاراسمپاتیک، تعادل بدن را حفظ می‌کند. سد خونی–مغزی از مغز در برابر مواد سمی محافظت می‌نماید. بیماری‌های نورولوژیک شامل اختلالات مغزی (مانند سکته و صرع)، نخاعی، اعصاب محیطی و عضلات هستند. از نظر علت می‌توانند عروقی، دمیلینه‌کننده، دژنراتیو یا عفونی باشند. تشخیص بر پایه معاینه، تصویربرداری و تست‌های الکتروفیزیولوژیک است و درمان شامل دارو، توانبخشی یا جراحی می‌باشد.")
    Category.objects.get_or_create(english_name='Nephrology', persian_name='بیماری‌های کلیه', unit=Decimal('1.5'), subject_status='Inactive', subject_image='subject/nephrology-subject.jpg', description="نفرولوژی شاخه‌ای از پزشکی است که به مطالعه و درمان بیماری‌های کلیه می‌پردازد؛ اندامی حیاتی که با فیلتر کردن خون، تعادل آب، الکترولیت‌ها و اسید–باز بدن را حفظ می‌کند و در تنظیم فشارخون و تولید هورمون‌هایی مانند اریتروپویتین نقش دارد. هر کلیه از میلیون‌ها نفرون تشکیل شده است که شامل گلومرول و توبول‌های مختلف برای تصفیه و بازجذب مواد هستند. بیماری‌های کلیه به دو دستهٔ اصلی تقسیم می‌شوند: حاد (Acute Kidney Injury) که با کاهش ناگهانی عملکرد کلیه همراه است، و مزمن (Chronic Kidney Disease) که به تدریج موجب کاهش برگشت‌ناپذیر عملکرد کلیه می‌شود. علل شایع شامل دیابت، فشارخون بالا، گلومرولونفریت‌ها و بیماری‌های پلی‌کیستیک است. تظاهرات بالینی می‌تواند شامل خستگی، ادم، افزایش اوره و کراتینین خون و اختلالات الکترولیتی باشد. تشخیص بر اساس آزمایش ادرار، کراتینین سرم، سونوگرافی و گاهی بیوپسی کلیه انجام می‌شود. درمان شامل کنترل علت زمینه‌ای، تنظیم فشارخون و در مراحل پیشرفته، دیالیز یا پیوند کلیه است.")
    Category.objects.get_or_create(english_name='Gastroenterology', persian_name='بیماری‌های گوارش و کبد', unit=Decimal('2.1'), subject_status='Inactive', subject_image='subject/gastroenterology-subject.jpg', description="گاستروانترولوژی شاخه‌ای از پزشکی است که به بررسی، تشخیص و درمان بیماری‌های دستگاه گوارش و کبد می‌پردازد؛ دستگاهی که از دهان تا مقعد امتداد دارد و مسئول هضم، جذب و دفع مواد غذایی است. معده با ترشح اسید و آنزیم‌ها در هضم نقش دارد و در برابر این اسید، لایهٔ موکوسی محافظ وجود دارد. زمانی که این تعادل با مصرف NSAIDها یا عفونت H. pylori برهم می‌خورد، گاستریت و زخم پپتیک ایجاد می‌شود. در مری، ضعف اسفنکتر تحتانی باعث بازگشت اسید و بروز بیماری ریفلاکس (GERD) می‌گردد. در رودهٔ باریک، بیماری سلیاک با واکنش ایمنی علیه گلوتن موجب تخریب پرزها و سوء‌جذب می‌شود. التهاب مزمن روده در قالب دو بیماری اصلی دیده می‌شود: کولیت اولسراتیو (درگیری پیوستهٔ کولون) و کرون (التهاب قطعه‌قطعه و عمقی). اختلالات عملکردی مانند سندروم روده تحریک‌پذیر (IBS) بدون آسیب بافتی ولی با درد و نفخ بروز می‌کنند. در کبد، هپاتیت‌های ویروسی، الکلی و متابولیک از علل شایع التهاب هستند و در موارد مزمن می‌توانند به سیروز، نارسایی کبد یا کارسینوم منجر شوند.")
    Category.objects.get_or_create(english_name='Pulmonology', persian_name='بیماری‌های ریه', unit=Decimal('1.9'), subject_status='Active', subject_image='subject/pulmonology-subject.jpg', description="پولمونولوژی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های دستگاه تنفسی می‌پردازد؛ سیستمی که شامل راه‌های هوایی، ریه‌ها و عروق ریوی است و وظیفه تبادل اکسیژن و دی‌اکسیدکربن و حفظ هموستاز اسید–باز را بر عهده دارد. ریه‌ها از میلیون‌ها آلوئول تشکیل شده که محل اصلی تبادل گازها هستند و جریان خون از طریق مویرگ‌های ریوی اکسیژن را به سلول‌ها منتقل می‌کند. بیماری‌های ریه به دو دستهٔ حاد و مزمن تقسیم می‌شوند: عفونت‌های حاد مانند پنومونی و برونشیت، و بیماری‌های مزمن مانند آسم، بیماری مزمن انسدادی ریه (COPD) و فیبروز ریوی که به تدریج عملکرد تنفسی را کاهش می‌دهند. علل شایع شامل عفونت‌های باکتریایی و ویروسی، قرارگیری در معرض دود و آلاینده‌ها، و عوامل ژنتیکی است. علائم بالینی می‌تواند شامل تنگی‌نفس، سرفه، خلط و خستگی باشد. تشخیص بر اساس رادیوگرافی قفسه سینه، سی‌تی اسکن، اسپیرومتری و آزمایش‌های خون و گازهای شریانی انجام می‌شود. درمان شامل کنترل علت زمینه‌ای، دارودرمانی، اکسیژن‌درمانی و در موارد پیشرفته تهویه مکانیکی یا پیوند ریه است.")
    Category.objects.get_or_create(english_name='Cardiology', persian_name='بیماری‌های قلب و عروق', unit=Decimal('1.9'), subject_status='Inactive', subject_image='subject/cardiology-subject.jpg', description="قلب و عروق شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های قلب و سیستم گردش خون می‌پردازد؛ سیستمی که با پمپاژ خون به اندام‌ها، اکسیژن و مواد مغذی را منتقل و دی‌اکسیدکربن و مواد زائد را دفع می‌کند. قلب از چهار حفره شامل دو دهلیز و دو بطن تشکیل شده و با سیستم الکتریکی داخلی خود، ضربان منظم و هماهنگ ایجاد می‌کند. عروق شامل شریان‌ها، وریدها و مویرگ‌ها هستند که فشار خون و جریان خون را تنظیم می‌کنند. بیماری‌های قلبی به دو دستهٔ حاد و مزمن تقسیم می‌شوند: اختلالات حاد مانند انفارکتوس میوکارد و آریتمی‌های شدید، و بیماری‌های مزمن مانند نارسایی قلب، ایسکمی مزمن و پرفشاری شریانی. علل شایع شامل تصلب شرایین، فشارخون بالا، دیابت، چاقی و عوامل ژنتیکی است. علائم بالینی می‌تواند شامل درد قفسه سینه، تنگی‌نفس، خستگی، ادم و سبکی سر باشد. تشخیص بر پایه الکتروکاردیوگرام، اکوکاردیوگرافی، آنژیوگرافی و آزمایش‌های خونی انجام می‌شود. درمان شامل اصلاح سبک زندگی، دارودرمانی، مداخلات آنژیوپلاستی و جراحی قلب و در موارد پیشرفته پیوند قلب است.")
    Category.objects.get_or_create(english_name='Endocrinology-and-Metabolism', persian_name='بیماری‌های غدد درون‌ریز و متابولیسم', unit=Decimal('1.9'), subject_status='Inactive', subject_image='subject/endocrinology-and-metabolism-subject.jpg', description="اندوکرینولوژی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های غدد درون‌ریز و اختلالات متابولیک می‌پردازد؛ غددی که با ترشح هورمون‌ها، عملکردهای حیاتی بدن مانند رشد، متابولیسم، تنظیم قند خون و تولید مثل را کنترل می‌کنند. غدد مهم شامل تیروئید، پاراتیروئید، پانکراس، غدد فوق‌کلیوی، هیپوفیز و غده جنسی هستند. اختلالات غدد می‌توانند موجب کم‌کاری یا پرکاری هورمونی شوند، مانند دیابت نوع ۱ و ۲، کم‌کاری یا پرکاری تیروئید، سندروم کوشینگ و بیماری آدیسون. بیماری‌های متابولیک اغلب با اختلال در قند، چربی یا الکترولیت‌ها همراه‌اند و می‌توانند اثر سیستمیک روی قلب، کلیه و استخوان‌ها داشته باشند. علائم بالینی شامل خستگی، کاهش یا افزایش وزن، ضعف عضلانی، تغییرات فشارخون و اختلالات قندی است. تشخیص بر اساس آزمایش‌های هورمونی، تصویرسازی غدد و آزمون‌های تحریک یا مهاری انجام می‌شود. درمان شامل اصلاح سبک زندگی، دارودرمانی هورمونی، جراحی غدد و در صورت نیاز تنظیم دقیق متابولیسم است.")
    Category.objects.get_or_create(english_name='Rheumatology', persian_name='بیماری‌های بافت همبند و روماتیسمی', unit=Decimal('1.5'), subject_status='Inactive', subject_image='subject/rheumatology-subject.jpg', description="روماتولوژی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های بافت همبند و روماتیسمی می‌پردازد؛ بافت‌هایی که شامل مفاصل، رباط‌ها، تاندون‌ها، پوست و اندام‌های داخلی می‌شوند و پشتیبانی ساختاری و عملکردی بدن را فراهم می‌کنند. بیماری‌های روماتیسمی می‌توانند التهابی، خودایمنی یا دژنراتیو باشند و اغلب با درد مفصل، تورم، محدودیت حرکتی و خستگی همراه هستند. از شایع‌ترین بیماری‌ها می‌توان به آرتریت روماتوئید، لوپوس اریتماتوز سیستمیک (SLE)، اسکلرودرمی، پلی‌میوزیت و آرتروز اشاره کرد. علل شامل پاسخ ایمنی نابجای بدن، عوامل ژنتیکی و محیطی و اختلال در تولید یا عملکرد کلاژن و سایر پروتئین‌های بافت همبند است. بیماری‌ها ممکن است سیستمیک بوده و ارگان‌هایی مانند قلب، ریه و کلیه را درگیر کنند. تشخیص بر پایه معاینه بالینی، آزمایش‌های خودایمنی (ANA، RF، anti-CCP)، تصویربرداری مفصلی و در موارد خاص بیوپسی بافت است. درمان شامل دارودرمانی ضدالتهابی، سرکوب سیستم ایمنی، فیزیوتراپی و مدیریت علائم است و هدف آن کاهش التهاب، حفظ عملکرد مفاصل و پیشگیری از آسیب ارگان‌هاست.")
    Category.objects.get_or_create(english_name='Infectious-Diseases', persian_name='بیماری‌های عفونی و گرمسیری', unit=Decimal('1'), subject_status='Inactive', subject_image='subject/infectious-diseases-subject.jpg', description="عفونت‌شناسی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های ناشی از عوامل عفونی مانند باکتری‌ها، ویروس‌ها، قارچ‌ها و انگل‌ها می‌پردازد. این بیماری‌ها می‌توانند حاد یا مزمن، سیستمیک یا موضعی باشند و از طریق تماس مستقیم، هوا، غذا و ناقلین منتقل شوند. سیستم ایمنی میزبان نقش حیاتی در مهار و کنترل عفونت دارد و ضعف آن می‌تواند منجر به عفونت شدید یا فرصت‌طلب شود. بیماری‌های گرمسیری اغلب در مناطق خاص با شرایط محیطی و بهداشتی ویژه دیده می‌شوند و شامل مالاریا، تب دانگی، تیفوس و شیگلوز هستند. علائم بالینی شامل تب، خستگی، ضعف، درد عضلانی، اسهال و بثورات پوستی است و می‌تواند بسته به عامل عفونی متغیر باشد. تشخیص بر پایه آزمایش‌های میکروبیولوژیک، سرولوژی، PCR و تصویربرداری صورت می‌گیرد. درمان شامل داروهای ضد میکروبی، حمایت سیستمیک و در موارد شدید مراقبت ویژه است. پیشگیری از طریق واکسیناسیون، بهداشت محیط، کنترل ناقلین و رعایت اصول ایمنی غذایی و فردی اهمیت ویژه دارد.")
    Category.objects.get_or_create(english_name='Hematology-and-Oncology', persian_name='بیماری‌های خون و بدخیمی‌ها', unit=Decimal('1.9'), subject_status='Inactive', subject_image='subject/hematology-and-oncology-subject.jpg', description="هماتولوژی و انکولوژی شاخه‌ای از پزشکی است که به مطالعه، تشخیص و درمان بیماری‌های خون، مغز استخوان و بدخیمی‌ها می‌پردازد. سیستم خونی شامل سلول‌های قرمز، سفید و پلاکت‌ها است که وظیفه حمل اکسیژن، دفاع ایمنی و انعقاد خون را بر عهده دارند. اختلالات خونی می‌توانند شامل کم‌خونی‌ها، پلی‌سیتمی، لوسمی‌ها، لنفوم‌ها و اختلالات انعقادی باشند و علائمشان شامل خستگی، خونریزی، کبودی و افزایش عفونت‌هاست. بدخیمی‌ها شامل تومورهای جامد و خونی بوده و رشد کنترل‌نشده سلول‌ها و متاستاز ویژگی اصلی آن‌هاست. تشخیص بر اساس آزمایش‌های خون، بیوپسی مغز استخوان، نمونه‌گیری تومور و تصویربرداری انجام می‌شود. درمان شامل شیمی‌درمانی، رادیوتراپی، ایمنی‌درمانی، دارودرمانی هدفمند و در برخی موارد پیوند سلول‌های بنیادی است. مدیریت این بیماران نیازمند نظارت دقیق بر عوارض درمان، حمایت تغذیه‌ای و کنترل عفونت‌هاست و هدف آن بهبود بقای بیمار و کیفیت زندگی است.")
    Category.objects.get_or_create(english_name='Pediatrics', persian_name='بیماری‌های کودکان', unit=Decimal('1'), subject_status='Inactive', subject_image='subject/pediatrics-subject.jpg', description="پزشکی اطفال شاخه‌ای از پزشکی است که به مراقبت، پیشگیری، تشخیص و درمان بیماری‌های نوزادان، کودکان و نوجوانان می‌پردازد. کودکان دارای ویژگی‌های فیزیولوژیک، متابولیک و ایمنی متفاوتی نسبت به بزرگسالان هستند که در تشخیص و درمان بیماری‌ها اهمیت دارد. بیماری‌های شایع شامل عفونت‌های تنفسی و گوارشی، بیماری‌های متابولیک و غددی، اختلالات رشد و کم‌خونی‌هاست. نوزادان و کودکان همچنین در معرض بیماری‌های ژنتیکی و مادرزادی قرار دارند که می‌تواند بر اندام‌ها و عملکرد سیستمیک تأثیر بگذارد. علائم بالینی ممکن است شامل تب، استفراغ، اسهال، اختلال رشد، بی‌حالی و تغییر در الگوی تغذیه و خواب باشد. تشخیص بر اساس معاینه دقیق بالینی، آزمایش‌های خون و ادرار، تصویربرداری و در صورت نیاز تست‌های ژنتیکی انجام می‌شود. درمان شامل دارودرمانی، حمایت تغذیه‌ای، واکسیناسیون، توانبخشی و مراقبت‌های ویژه در نوزادان و کودکان است. پیشگیری، آموزش والدین و پیگیری رشد و نمو کودک از ارکان اصلی پزشکی اطفال محسوب می‌شوند.")

def create_initial_records_hospital(apps, schema_editor): 
    Category = apps.get_model('classroom', 'Hospital') 
    Category.objects.get_or_create(
        english_name="alzahra",
        persian_name="مرکز آموزشی درمانی الزهرا(س)",
        type="public Hospital",
        established_year="1986-01-01",
        address="اصفهان، بلوار صفه، مرکز آموزشی درمانی الزهرا (س)",
        city="اصفهان",
        province="اصفهان",
        phone_number="03136202020",
        email="",
        website="alzahra.mui.ac.ir",
        capacity=750,
        description= "بیمارستان الزهرا (س) اصفهان یک مرکز آموزشی درمانی درجه یک وابسته به دانشگاه علوم پزشکی اصفهان است. این بیمارستان در وسعت ۲۷ هکتار و بنا به اطلاعات رسمی دارای ۷۵۰ تخت فعال و ۳۳ درمانگاه تخصصی است:]{. امکانات تخصصی شامل دستگاه‌های MRI، سی‌تی‌اسکن‌های ۱۶ و ۱۲۸ اسلایس، آنژیوگرافی قلب، بخش پیوند اعضا، و سایر بخش‌های تخصصی مانند جراحی قلب باز، جراحی اعصاب و پیوند مغز استخوان را در بر می‌گیرد. این مرکز علاوه بر خدمات عمومی، خدمات فوق تخصصی پزشکی (مانند پیوند کبد، جراحی‌های پیشرفته مغز و ستون فقرات و سایر تخصص‌ها) را نیز ارائه می‌دهد."
    )
    Category.objects.get_or_create(
        english_name="seyed_o_shohada",
        persian_name="مجتمع آموزشی درمانی سیدالشهداء(ع)",
        type="public Hospital",
        established_year="1971-01-01",
        address="اصفهان، خیابان خیام، کوی نهر فرشادی، بیمارستان سیدالشهداء",
        city="اصفهان",
        province="اصفهان",
        phone_number="03132350218",
        email="omid@mui.ac.ir",
        website="omid.mui.ac.ir",
        capacity=185,
        description="مجتمع آموزشی درمانی سیدالشهداء (امید) اصفهان بیمارستان تخصصی سرطان و انکولوژی وابسته به دانشگاه علوم پزشکی اصفهان است."
    )
    Category.objects.get_or_create(
        english_name="emam_kazem",
        persian_name="مرکز آموزشی درمانی امام موسی کاظم(ع)",
        type="public Hospital",
        established_year="1990-01-01",
        address="پل چمران، خیابان کاوه جنوبی، مرکز درمانی سوانح سوختگی امام موسی کاظم (ع)",
        city="اصفهان",
        province="اصفهان",
        phone_number="03133457670",
        email="i.m.kazem.hospital@mui.ac.ir",
        website="savaneh.mui.ac.ir",
        capacity=100,
        description="مرکز حوادث و حریق های شدید استان اصفهان"
    )
    Category.objects.get_or_create(
        english_name="amin",
        persian_name="مرکز آموزشی درمانی امین",
        type="public Hospital",
        established_year="1969-01-01",
        address="اصفهان، خیابان ابن سینا، کوچه سنبلستان، بیمارستان امین",
        city="اصفهان",
        province="اصفهان",
        phone_number="03134455051",
        email="amin@mui.ac.ir",
        website="amin.mui.ac.ir",
        capacity=181,
        description="مرکز آموزشی درمانی امین اصفهان یکی از قدیمی‌ترین بیمارستان‌های عمومی اصفهان است که در سال ۱۳۴۸ (۱۹۶۹) تأسیس گردید. این بیمارستان که زیرنظر دانشگاه علوم پزشکی اصفهان اداره می‌شود، دارای ۱۸۱ تخت فعال می‌باشد. "
    )
    Category.objects.get_or_create(
        english_name="kashani",
        persian_name="مرکز آموزشی درمانی آیت الله کاشانی",
        type="public Hospital",
        established_year="1953-01-01",
        address="اصفهان، خیابان آیت الله کاشانی جنوبی، بیمارستان آیت الله کاشانی",
        city="اصفهان",
        province="اصفهان",
        phone_number="03132330091",
        email="kashani@mui.ac.ir",
        website="kashani.mui.ac.ir",
        capacity=181,
        description=" "
    )
    Category.objects.get_or_create(
        english_name="emam_hossein",
        persian_name="مرکز کودکان حضرت امام حسین(ع)",
        type="public Hospital",
        established_year="2012-01-01",
        address="اصفهان، کیلومتر ۱۰ خیابان امام خمینی، مرکز آموزشی درمانی کودکان حضرت امام حسین (ع)",
        city="اصفهان",
        province="اصفهان",
        phone_number="03133866266",
        email="emamhossein_hospital@mui.ac.ir",
        website="ehuch.mui.ac.ir",
        capacity=168,
        description="بیمارستان کودکان امام حسین(ع)"
    )
    Category.objects.get_or_create(
        english_name="eisa",
        persian_name="بیمارستان عیسی بن مریم(ع)",
        type="public Hospital",
        established_year="1904-01-01",
        address="اصفهان - خیابان شمس آبادی - بیمارستان عیسی بن مریم (ع) ",
        city="اصفهان",
        province="اصفهان",
        phone_number="03132332065",
        email="isa@mui.ac.ir",
        website="isa.mui.ac.ir",
        capacity=126,
        description="بیمارستان عیسی بن مریم (ع) اصفهان، که سابقاً به عنوان بیمارستان مسیحی معروف بود، یک بیمارستان عمومی آموزشی وابسته به دانشگاه علوم پزشکی اصفهان است."
    )
    Category.objects.get_or_create(
        english_name="khorshid",
        persian_name="مرکز آموزشی درمانی خورشید",
        type="public Hospital",
        established_year="1921-01-01",
        address="اصفهان - خیابان استانداری",
        city="اصفهان",
        province="اصفهان",
        phone_number="03133033740",
        email="nour@mui.ac.ir",
        website="nour.mui.ac.ir",
        capacity=224,
        description="بیمارستان خورشید (نور)"
    )
    Category.objects.get_or_create(
        english_name="beheshti",
        persian_name="مرکز آموزشی درمانی شهید بهشتی",
        type="public Hospital",
        established_year="1971-01-01",
        address="اصفهان - پل فلزی - ابتدای خیابان مطهری",
        city="اصفهان",
        province="اصفهان",
        phone_number="03132367001",
        email="beheshti@mui.ac.ir",
        website="beheshti.mui.ac.ir",
        capacity=120,
        description=" "
    )
    Category.objects.get_or_create(
        english_name="chamran",
        persian_name="مرکز آموزشی درمانی و پژوهشی قلب شهید چمران",
        type="public Hospital",
        established_year="1966-01-01",
        address="اصفهان - میدان بزرگمهر - خیابان مشتاق سوم",
        city="اصفهان",
        province="اصفهان",
        phone_number="03133033710",
        email="chamran@mui.ac.ir",
        website="chamran.mui.ac.ir",
        capacity=224,
        description="بیمارستان قلب شهید چمران"
    )
    Category.objects.get_or_create(
        english_name="farabi",
        persian_name="مجتمع تخصصی و فوق تخصص فارابی",
        type="public Hospital",
        established_year="1977-01-01",
        address="اصفهان - خیابان مشتاق سوم - بلوار ارغوانیه",
        city="اصفهان",
        province="اصفهان",
        phone_number="03135312020",
        email="farabi@mui.ac.ir",
        website="farabi.mui.ac.ir",
        capacity=342,
        description="مجتمع تخصصی و فوق‌تخصصی فارابی اصفهان یک بیمارستان بزرگ تخصصی وابسته به دانشگاه علوم پزشکی اصفهان است"
    )
    Category.objects.get_or_create(
        english_name="feiz",
        persian_name="مرکز آموزشی درمانی فیض",
        type="public Hospital",
        established_year="1963-01-01",
        address="اصفهان - میدان قدس - ابتدای خیابان مدرس",
        city="اصفهان",
        province="اصفهان",
        phone_number="03134452038",
        email="feiz@mui.ac.ir",
        website="feiz.mui.ac.ir",
        capacity=118,
        description="بیمارستان آموزشی درمانی فیض اصفهان یک مرکز تخصصی چشم و جراحی عمومی است"
    )
    Category.objects.get_or_create(
        english_name="zeynab",
        persian_name="بیمارستان حضرت زینب",
        type="public Hospital",
        established_year="1991-01-01",
        address="اصفهان، زینبیه، چهارراه عاشق اصفهانی، خیابان آیت‌الله غفاری، بیمارستان حضرت زینب (س)",
        city="اصفهان",
        province="اصفهان",
        phone_number="03135511195",
        email="zeynabhospital@mui.ac.ir",
        website="zeynabhospital.mui.ac.ir",
        capacity=46,
        description="بیمارستان حضرت زینب (س) اصفهان یک مرکز تخصصی زنان، زایمان و بهداشت مادران و نوزادان است"
    )

def create_initial_records_hospitalsubject(apps, schema_editor): 
    Category = apps.get_model('classroom', 'HospitalSubject')
    Subject = apps.get_model('classroom', 'Subject')
    subject_name = "Pulmonology"
    subject_record = Subject.objects.get(english_name=subject_name)
    Hospital = apps.get_model('classroom', 'Hospital')
    hospital_name = "alzahra"
    hospital_record = Hospital.objects.get(english_name=hospital_name) 
    Category.objects.get_or_create(hospital=hospital_record, subject=subject_record, access_status=True)
    hospital_name = "farabi"
    hospital_record = Hospital.objects.get(english_name=hospital_name) 
    Category.objects.get_or_create(hospital=hospital_record, subject=subject_record, access_status=True)
    hospital_name = "chamran"
    hospital_record = Hospital.objects.get(english_name=hospital_name) 
    Category.objects.get_or_create(hospital=hospital_record, subject=subject_record, access_status=True)
    hospital_name = "khorshid"
    hospital_record = Hospital.objects.get(english_name=hospital_name) 
    Category.objects.get_or_create(hospital=hospital_record, subject=subject_record, access_status=True)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_name', models.CharField(default=None, max_length=50, unique=True)),
                ('persian_name', models.CharField(default=None, max_length=50)),
                ('type', models.CharField(choices=[('Public Hospital', 'Government Hospital'), ('Private Hospital', 'Private'), ('Social Security Hospital', 'Social Security'), ('Charitable Hospital', 'Charitable'), ('Military Hospital', 'Military'), ('Semi-private Hospital', 'Semi-private')], max_length=30)),
                ('established_year', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField()),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_name', models.CharField(default=None, max_length=50, unique=True)),
                ('persian_name', models.CharField(default=None, max_length=50, unique=True)),
                ('unit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField(max_length=1000)),
                ('subject_image', models.ImageField(blank=True, default='defaults/default_subject.jpg', null=True, upload_to='subject/')),
                ('subject_status', models.CharField(choices=[('Active', 'A'), ('Inactive', 'I')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('student_count', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'A'), ('Closed', 'Cl'), ('Finished', 'F'), ('Created', 'Cr')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='section/')),
                ('description', models.TextField(max_length=1000)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='class.semester')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='class.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_status', models.CharField(choices=[('Active', 'A'), ('Blocked', 'B')], max_length=10)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectionstudents', to='class.section')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentsections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentsubjects', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectstudents', to='class.subject')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_status', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalsubjects', to='class.hospital')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjecthospitals', to='class.subject')),
            ],
        ),
        migrations.RunPython(create_initial_records_subject),
        migrations.RunPython(create_initial_records_semester),
        migrations.RunPython(create_initial_records_hospital),
        migrations.RunPython(create_initial_records_hospitalsubject),
    ]
