# Generated by Django 5.2.7 on 2026-02-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_credittransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
