# Generated by Django 5.2.7 on 2026-02-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital/'),
        ),
    ]
