# Generated by Django

from django.db import migrations, models

def update_hospital_images(apps, schema_editor):
    Hospital = apps.get_model('classroom', 'Hospital')
    
    hospital_images = {
        "alzahra": "hospital/alzahra.jpg",
        "khorshid": "hospital/khorshid.jpg",
        "chamran": "hospital/chamran.jpg",
        "farabi": "hospital/farabi.jpg",
    }
    
    for english_name, image_path in hospital_images.items():
        Hospital.objects.filter(english_name=english_name).update(hospital_image=image_path)

def reverse_hospital_images(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_hospital_hospital_image'), 
    ]

    operations = [
        # ۱. ابتدا فیلد تصویر را به جدول اضافه می‌کنیم
        migrations.AddField(
            model_name='hospital',
            name='hospital_image',
            field=models.ImageField(blank=True, default='defaults/default_hospital.jpg', null=True, upload_to='hospital/'),
        ),
        # ۲. سپس دیتای رکوردهای قبلی را آپدیت می‌کنیم
        migrations.RunPython(update_hospital_images, reverse_code=reverse_hospital_images),
    ]