# Generated by Django 5.2.7 on 2026-02-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_hospital_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital/'),
        ),
    ]
