# Generated by Django 5.2.7 on 2025-11-13 21:14

import uuid
from django.db import migrations, models

def create_initial_records_semester(apps, schema_editor): 
    Category = apps.get_model('pulmonology_scenario', 'OptimalCostPulmonologyParaclinic') 
    Category.objects.get_or_create(english_name='Asthma', persian_name='آسم', optimal_cost=1440000)
    Category.objects.get_or_create(english_name='Pneumonia', persian_name='پنومونی', optimal_cost=2215000)
    Category.objects.get_or_create(english_name='COPD', persian_name='بیماری مزمن انسدادی ریه', optimal_cost=3390000)
    Category.objects.get_or_create(english_name='PTE', persian_name='آمبولی ریه', optimal_cost=4160000)
    Category.objects.get_or_create(english_name='IPF', persian_name='فیبروز ریه', optimal_cost=5440000)
    Category.objects.get_or_create(english_name='PH', persian_name='فشارخون ریوی', optimal_cost=6560000)
    Category.objects.get_or_create(english_name='Pleural Effusion', persian_name='اختلالات پلور', optimal_cost=6185000)
    Category.objects.get_or_create(english_name='ARDS', persian_name='سندرم زجر تنفسی حاد', optimal_cost=7685000)

def create_initial_records_semester(apps, schema_editor): 
    Category = apps.get_model('pulmonology_scenario', 'CostPulmonologyParaclinic') 
    Category.objects.get_or_create(name='CBC', slug_name='CBC', min_cost=60000, max_cost=100000)
    Category.objects.get_or_create(name='ESR/CRP', slug_name='ESR_CRP', min_cost=50000, max_cost=120000)
    Category.objects.get_or_create(name='BMP', slug_name='BMP', min_cost=100000, max_cost=200000)
    Category.objects.get_or_create(name='LFTs', slug_name='LFTs', min_cost=150000, max_cost=300000)
    Category.objects.get_or_create(name='VBG', slug_name='VBG', min_cost=50000, max_cost=100000)
    Category.objects.get_or_create(name='Sputum analysis', slug_name='sputum_analysis', min_cost=50000, max_cost=100000)
    Category.objects.get_or_create(name='Sputum AFB', slug_name='sputum_AFB', min_cost=100000, max_cost=200000)
    Category.objects.get_or_create(name='Alpha-1 antitrypsin level', slug_name='alpha1_antitrypsin_level', min_cost=400000, max_cost=800000)
    Category.objects.get_or_create(name='D-dimer', slug_name='D_dimer', min_cost=400000, max_cost=600000)
    Category.objects.get_or_create(name='BNP/NT-proBNP', slug_name='BNP_NT_proBNP', min_cost=400000, max_cost=700000)
    Category.objects.get_or_create(name='HIV test', slug_name='HIV_test', min_cost=200000, max_cost=400000)
    Category.objects.get_or_create(name='Autoimmune panel', slug_name='autoimmune_panel', min_cost=1000000, max_cost=2500000)
    Category.objects.get_or_create(name='Chest X-Ray', slug_name='chest_X_ray', min_cost=300000, max_cost=800000)
    Category.objects.get_or_create(name='Chest CT', slug_name='chest_CT', min_cost=600000, max_cost=1000000)
    Category.objects.get_or_create(name='CTPA', slug_name='CTPA', min_cost=1500000, max_cost=2500000)
    Category.objects.get_or_create(name='MRI Chest', slug_name='MRI_chest', min_cost=2500000, max_cost=4000000)
    Category.objects.get_or_create(name='PET Scan', slug_name='PET_scan', min_cost=10000000, max_cost=30000000)
    Category.objects.get_or_create(name='Spirometry', slug_name='spirometry', min_cost=300000, max_cost=600000)
    Category.objects.get_or_create(name='Plethysmography', slug_name='plethysmography', min_cost=500000, max_cost=1000000)
    Category.objects.get_or_create(name='Bronchoscopy', slug_name='bronchoscopy', min_cost=3000000, max_cost=7000000)
    Category.objects.get_or_create(name='Thoracentesis', slug_name='thoracentesis', min_cost=2000000, max_cost=5000000)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostPulmonologyParaclinic',
            fields=[
                ('pulmonologyparaclinic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('min_cost', models.IntegerField()),
                ('max_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OptimalCostPulmonologyParaclinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('optimal_cost', models.IntegerField()),
            ],
        ),
    ]
