# Generated by Django 5.2.7 on 2025-11-17 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostPulmonologyParaclinic',
            fields=[
                ('pulmonologyparaclinic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug_name', models.CharField(default=None, max_length=50, unique=True)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('min_cost', models.IntegerField()),
                ('max_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OptimalCostPulmonologyParaclinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_name', models.CharField(default=None, max_length=50, unique=True)),
                ('persian_name', models.CharField(default=None, max_length=50, unique=True)),
                ('optimal_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PulmonologyDisease',
            fields=[
                ('disease_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_name', models.CharField(default=None, max_length=50, unique=True)),
                ('persian_name', models.CharField(default=None, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PulmonologyFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('feedback', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PulmonologyScenario',
            fields=[
                ('scenario_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scenario', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
