# Generated by Django 5.2.7 on 2025-11-14 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulmonologyDisease',
            fields=[
                ('disease_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_name', models.CharField(default=None, max_length=50, unique=True)),
                ('persian_name', models.CharField(default=None, max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='optimalcostpulmonologyparaclinic',
            old_name='name',
            new_name='english_name',
        ),
        migrations.AddField(
            model_name='costpulmonologyparaclinic',
            name='slug_name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='optimalcostpulmonologyparaclinic',
            name='persian_name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
