# Generated by Django 5.2.7 on 2025-11-21 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0002_pulmonologyscenario_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulmonologyscenario',
            name='student',
        ),
        migrations.AddField(
            model_name='pulmonologyscenario',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('student_log', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentlog', to='pulmonology_scenario.pulmonologyscenario')),
            ],
        ),
    ]
