# Generated by Django 5.2.7 on 2025-11-16 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0002_pulmonologydisease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulmonologyFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('feedback', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PulmonologyScenario',
            fields=[
                ('scenario_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scenario', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
