# Generated by Django 5.2.7 on 2025-11-22 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0004_pulmonologyscenario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulmonologyfeedback',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbackpulmonologyscenario', to='pulmonology_scenario.pulmonologyscenario'),
        ),
        migrations.AddField(
            model_name='pulmonologyfeedback',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pulmonologyscenario',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulmonologydiseasescenario', to='pulmonology_scenario.pulmonologydisease'),
        ),
    ]
