# Generated by Django 5.2.7 on 2025-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0006_pulmonologyfeedback_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulmonologydisease',
            name='type_disease',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='pulmonologydisease',
            name='english_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='pulmonologydisease',
            name='persian_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
