# Generated by Django 5.2.7 on 2025-12-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0008_populate_disease_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulmonologyscenario',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
