# Generated by Django 5.2.7 on 2025-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0009_pulmonologyscenario_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulmonologyfeedback',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
