# Generated by Django 5.2.7 on 2026-01-07 20:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0011_remove_pulmonologyfeedback_evaluation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaclinicTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('persian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('optimal_cost', models.IntegerField(help_text='هزینه ایده\u200cآل برای امتیازدهی')),
                ('min_cost', models.IntegerField(default=0)),
                ('max_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(verbose_name='Scenario Logic JSON')),
                ('tracking_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='pulmonology_scenario.pulmonologydisease')),
            ],
        ),
        migrations.CreateModel(
            name='UserScenarioAttempt',
            fields=[
                ('attempt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_done', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scenario_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='pulmonology_scenario.scenariotemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='CostPulmonologyParaclinic',
        ),
        migrations.DeleteModel(
            name='OptimalCostPulmonologyParaclinic',
        ),
        migrations.RemoveField(
            model_name='pulmonologyfeedback',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='studentlog',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='pulmonologyfeedback',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='pulmonologyfeedback',
            name='tracking_code',
        ),
        migrations.RemoveField(
            model_name='studentlog',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='studentlog',
            name='student_log',
        ),
        migrations.AddField(
            model_name='pulmonologyfeedback',
            name='feedback_content',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studentlog',
            name='action_log',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studentlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pulmonologyfeedback',
            name='feedback_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='log_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pulmonologyfeedback',
            name='attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='pulmonology_scenario.userscenarioattempt'),
        ),
        migrations.AddField(
            model_name='studentlog',
            name='attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pulmonology_scenario.userscenarioattempt'),
        ),
        migrations.DeleteModel(
            name='PulmonologyScenario',
        ),
    ]
