# Generated by Django 5.2.7 on 2026-01-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0012_paraclinictest_scenariotemplate_userscenarioattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulmonologyfeedback',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
