# Generated by Django 5.2.7 on 2026-02-04 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_studentcredit'),
        ('pulmonology_scenario', '0013_pulmonologyfeedback_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariotemplate',
            name='related_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='classroom.subject'),
        ),
        migrations.CreateModel(
            name='DailyScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_instances', to='pulmonology_scenario.scenariotemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='pulmonology_date_bbb7df_idx')],
                'unique_together': {('scenario_template', 'date')},
            },
        ),
    ]
