# Generated by Django 5.2.7 on 2026-02-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulmonology_scenario', '0014_scenariotemplate_related_subject_dailyscenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulmonologyfeedback',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
