# Generated by Django 5.2.7 on 2026-02-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_hospital_hospital_image'),
        ('pulmonology_scenario', '0015_pulmonologyfeedback_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscenarioattempt',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_attempts', to='classroom.section'),
        ),
    ]
