# Generated by Django 5.2.7 on 2026-02-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درسنامه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'درسنامه',
                'verbose_name_plural': 'درسنامه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TutorialPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صفحه (زیرعنوان)')),
                ('content', models.TextField(verbose_name='محتوای صفحه')),
                ('page_number', models.PositiveIntegerField(verbose_name='شماره صفحه / ترتیب')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tutorial.tutorial', verbose_name='درسنامه مربوطه')),
            ],
            options={
                'verbose_name': 'صفحه درسنامه',
                'verbose_name_plural': 'صفحات درسنامه',
                'ordering': ['page_number'],
                'unique_together': {('tutorial', 'page_number')},
            },
        ),
    ]
