# Generated by Django 5.2.7 on 2026-02-12 11:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tutorialpage',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='tutorialpage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='id',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tutorialpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialpage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorialpage',
            name='page_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tutorialpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tutorialpage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutorialpage',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorialpage',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tutorial.tutorial'),
        ),
        migrations.RemoveField(
            model_name='tutorialpage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tutorialpage',
            name='page_number',
        ),
    ]
