# Generated by Django 5.2.7 on 2026-02-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialpage',
            name='x_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
